Updates wording
centrifuge/apps pull request #1189
Opened 2023-02-09 10:38 UTC by Hornebom

### Ticket
https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/gh/centrifuge/apps/1185

### Approvals

- [ ] Product

2023-02-09 15:25 UTC, annamehr commented
Sorry made a mistake it should be 
* Change label of Remove from whitelist to `Remove from memberlist`

and I spotted one missing piece
* `Remove from Investor whitelist ` should be `Remove from investor memberlist`

<img width="1126" alt="Screenshot 2023-02-09 at 16 20 31" src="https://user-images.githubusercontent.com/31280003/217855826-7672cac4-b549-4281-bc37-b51326074682.png">

2023-02-10 08:55 UTC, annamehr requested changes
Added my proposed changes in the comments

2023-02-14 09:26 UTC, onnovisser approved these changes

2023-02-14 09:30 UTC, onnovisser commented on centrifuge-app/src/pages/IssuerPool/Investors/index.tsx
> +                      {isAllowed ? 'Remove action' : 'Add token'}
why not just `Remove from memberlist` and `Add to memberlist` ?

2023-02-16 11:00 UTC, merged