Verification state in WalletMenu
centrifuge/apps pull request #1309
Opened 2023-04-14 14:32 UTC by Hornebom

### Description
- moves OnboardingProvider up in the component tree -> enable usage of OnboardingUser to whole application
- adds useVerificationStatus hook
- creates OnboardingStatus for usage within WalletMenu
- extends WalletMenu with optional menuItems prop
- extends AnchorButton -> use react-router Link for internal navigation

### Approvals
- [ ] Dev
- [ ] Product

### Impact

Regarding changes to `AnchorButton`, internal links (or what should be `<a>` and not `<button>`) can be refactored

2023-04-15 02:47 UTC, jpangelle commented
What about making the `In progress...` text clickable or a button or something and that would direct the user to `/onboarding`?
<img width="259" alt="image" src="https://user-images.githubusercontent.com/28536523/232179453-644f34c0-ff6a-4bb4-8ab7-009a52817aea.png">

2023-04-15 03:15 UTC, jpangelle commented on centrifuge-app/src/components/OnboardingProvider.tsx
> +}
Since non-us based investors do not need to complete the accreditation step, you will have to add some logic to handle that case.

```ts
export const useVerificationStatus = (): VerificationStatus => {
  const { onboardingUser } = useOnboarding();

  const requiredGlobalSteps = Object.keys(onboardingUser.globalSteps).filter(
    (globalStep) => {
      if (
        (onboardingUser.investorType === 'individual' &&
          onboardingUser.countryOfCitizenship === 'us') ||
        (onboardingUser.investorType === 'entity' &&
          onboardingUser.jurisdictionCode.startsWith('us'))
      ) {
        return true;
      } else {
        return globalStep !== 'verifyAccreditation';
      }
    }
  );

  return onboardingUser
    ? requiredGlobalSteps.every(
        (step) => onboardingUser.globalSteps[step].completed
      )
      ? 'verified'
      : 'pending'
    : 'unverified';
};
```

2023-04-15 03:16 UTC, jpangelle requested changes
left a few comments 💯

2023-04-17 11:36 UTC, Hornebom commented
> What about making the `In progress...` text clickable or a button or something and that would direct the user to `/onboarding`? <img alt="image" width="259" src="https://user-images.githubusercontent.com/28536523/232179453-644f34c0-ff6a-4bb4-8ab7-009a52817aea.png">

Added link to onboarding view:
<img width="237" alt="Screenshot 2023-04-17 at 13 35 42" src="https://user-images.githubusercontent.com/7050932/232473192-d93d4906-f47d-478e-b31f-9e077f8cbace.png">

2023-04-17 11:55 UTC, jpangelle commented on centrifuge-app/src/components/Root.tsx
> +        {/* <OnboardingProvider> */}
can remove commented code

2023-04-17 11:55 UTC, jpangelle commented on fabric/src/stories/Icons.stories.tsx
> -  // component: () => null,
remove commented code

2023-04-17 11:56 UTC, jpangelle approved these changes
😎 💸

2023-04-17 11:59 UTC, Hornebom commented on centrifuge-app/src/components/Root.tsx
> +        {/* <OnboardingProvider> */}
Removed 👌

2023-04-18 08:40 UTC, annamehr commented
Found a bug: When testing the individual onboarding flow, I did not receive an email to confirm my email address.

2023-04-20 08:11 UTC, onnovisser approved these changes

2023-04-20 15:52 UTC, merged