added ipfs hash fetching method to tinlake.js
centrifuge/apps pull request #28
Opened 2020-12-07 12:12 UTC by charleenfei

2020-12-10 19:10 UTC, charleenfei commented
closes #8

2020-12-10 19:11 UTC, charleenfei commented on tinlake-ui/next.config.js
> -  },
i had to remove this redirect section due to the new async way we have of fetching the pool config

2020-12-10 19:15 UTC, charleenfei commented
closes #8

2020-12-14 09:01 UTC, offerijns requested changes
Code looks great, just a few comments! As mentioned on Slack, we do need to first push the latest mainnet pools to the registry, and then double check that everything works correctly, before we can merge this.

2020-12-14 13:37 UTC, philipstanislaus reviewed
Nice, thanks @charleenfei ! 🎉 

Thinking about this architecture some more, I wonder whether it makes sense to dynamically load data from IPFS on the client side.

If I understand this correctly, the pool pages can't dynamically be updated anyways (through a new entry in the on-chain pool registry and new data on IPFS), since we statically create the paths at build time. 

If we wanted dynamic pools, we'd have to remove static paths or change the static path logic to use dynamic fallback (see [Next.js docs for more](https://nextjs.org/docs/basic-features/data-fetching#the-fallback-key-required)). 

What has been implemented here should impact the page's speed quite a bit, since there is 1 request to an Infura node, and afterwards 1 request to an IPFS node. Both of those are done on every page load from the client side. 

We could mitigate that performance hit by using server side rendering and cache the responses to the Ethereum/IPFS requests to happen every 15 seconds in the background.

Alternatively, we could use your logic in the static path hooks only to stay completely static. This has the upside of being very simple, fast, but requires a rebuild/export of the app whenever we add/remove pools.

Can we quickly discuss those trade-offs? Thanks!

2020-12-15 14:44 UTC, philipstanislaus approved these changes
Nice, just a few minor comments 🎉

2020-12-15 14:44 UTC, philipstanislaus commented on tinlake-ui/components/PoolLink/index.tsx
> +  as: string | null | undefined | UrlObject
Again, I think we should change them to: 

```suggestion
  root: string | undefined,
  slug: string | undefined,
  as: string | null | undefined
```

2020-12-15 14:44 UTC, philipstanislaus commented on tinlake-ui/components/PoolLink/index.tsx
> +function getHref(root: string | string[] | undefined, href: string | null | undefined | UrlObject): string {
These types are not correct anymore, right? I guess the following would be right: 

```suggestion
function getHref(root: string | undefined, href: string | null | undefined): string {
```

2020-12-15 14:44 UTC, philipstanislaus commented on tinlake-ui/components/PoolLink/index.tsx
> +  if (root) {
This needs to be a check for `slug`, right?

```suggestion
  if (slug) {
```

2020-12-15 14:44 UTC, philipstanislaus commented on tinlake-ui/components/PoolLink/index.tsx
> +  if (root) {
This should test for `slug` again, right? 

```suggestion
  if (slug) {
```

2020-12-15 14:44 UTC, philipstanislaus commented on tinlake-ui/components/ValueNFT/index.tsx
> +  console.log(props.tokenId, 'TOKEN ID VALUE')
Can we remove this?

2020-12-15 15:59 UTC, charleenfei commented on tinlake-ui/components/PoolLink/index.tsx
> +function getHref(root: string | string[] | undefined, href: string | null | undefined | UrlObject): string {
the types are correct, the typing for router.query.root must also include string[]

2020-12-15 16:00 UTC, charleenfei commented on tinlake-ui/components/PoolLink/index.tsx
> +  as: string | null | undefined | UrlObject
please see comment above

2020-12-15 18:00 UTC, offerijns approved these changes
LGTM!

2020-12-15 18:05 UTC, merged