Set up integrated onboarding MVP
centrifuge/apps pull request #3
Opened 2020-11-23 12:23 UTC by offerijns

2020-12-07 20:51 UTC, philipstanislaus requested changes
This is awesome @offerijns 🎉 

I left maybe a bit too many comments, but you asked for it ;) 

General notes: 
1. There are no tests, but this the api is super critical (privacy and functionality wise, downtime/bugs will cost us users). Let's discuss how we want to approach that.
2. There is no retry handling for requests to 3rd party services. I feel we should add that (potentially in the next iteration) to make sure we don't loose users due to networking issues etc.
3. Before merging, can we transform all security and conversion related TODOs into issues (e. g. potential drop outs of funnel)?
4. Note to ourselves: For production, we should use some stack tracing/logging service.
5. Note to ourselves: we need opt-in for cookie in onboarding modal.

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +  email varchar(255),
Did we decide we want to store those in plaintext?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +    address character varying(100) not null,
Unique index on `blockchain`, `network` and `lower(address)` is needed to speed up the lookups below.

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +    user_id uuid not null references users(id) on delete cascade on update cascade,
Index by `lower(address)` is necessary, since we find users by address below

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +  email varchar(255),
Unique index by email?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +create unique index if not exists kyc_unique on kyc (user_id, provider, provider_account_id);
This index should probably be on `provider` and `provider_account_id`, right?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +create unique index if not exists agreements_unique on agreements (user_id, provider, provider_envelope_id);
Again, this should be on `provide`, `provider_envelope_id`, right?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +    pool_id character(42) not null,
Nitpicking, but should we not store this as raw bytes to save space? 🙈

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/main.ts
> +  app.use(cookieParser())
Do we really need cookies? Why?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/repos/db.service.ts
> +  sql: postgres.Sql<{}> | undefined
Can it really be undefined?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/repos/address.repo.ts
> +  async find(address: string): Promise<Address | undefined> {
There could be duplicate addresses, e. g. if someone is using the same address on both Ethereum mainnet and Kovan. Can we change the logic here to be similar to line 30?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +create unique index if not exists agreements_unique on agreements (user_id, provider, provider_envelope_id);
Should also add an index for `user_id` here to speed up those lookups.

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +create unique index if not exists agreements_unique on agreements (user_id, provider, provider_envelope_id);
And we also need an index by `user_id`, `pool_id`, `provider_template_id`

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/repos/agreement.repo.ts
> +  async hasBeenSigned(agreementId: string): Promise<Agreement | undefined> {
`has` sounds to me as if this is a query, can we instead call this `setSigned`?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/repos/agreement.repo.ts
> +  async hasBeenCounterSigned(agreementId: string): Promise<Agreement | undefined> {
Again, can we call this 

```suggestion
  async setCounterSigned(agreementId: string): Promise<Agreement | undefined> {
```

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +create unique index if not exists kyc_unique on kyc (user_id, provider, provider_account_id);
There also needs to be a index here on `user_id` for faster lookups.

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/docusign-auth.service.ts
> +    return `${process.env.DOCUSIGN_ACCOUNT_API_HOST}oauth/auth?response_type=code&scope=signature%20impersonation&client_id=${process.env.DOCUSIGN_INTEGRATION_KEY}&state=a39fh23hnf23&redirect_uri=htt
What is `state` in here? 

Also `redirect_uri` should go into an env variable, right?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/docusign-auth.service.ts
> +      exp: unixNow + 3600,
Can we put the `3600` here and in line 50 into a constant in this file?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/docusign.service.ts
> +          email: 'jeroen+issuer@centrifuge.io',
Put this into env?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/docusign.service.ts
> +    // TODO: email and userName here should be taken from Securitize
That can happen from the controller, right?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/docusign.service.ts
> +      returnUrl: returnUrl || 'https://tinlake.centrifuge.io/',
Instead of redirecting to a default URL, can we require the `returnUrl` and fail starting the onboard API if it is not set?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/kyc/securitize.service.ts
> +    const redirectUrl = `http://localhost:3100/pools/${poolId}/callback/${address}/securitize`
Put this into env?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/kyc/securitize.service.ts
> +    const url = `https://id.sandbox.securitize.io/#/authorize?issuerId=${process.env.SECURITIZE_CLIENT_ID}&scope=${scope}&redirecturl=${redirectUrl}`
Likewise with this URL => env :)

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/services/kyc/securitize.service.ts
> +  async getInvestor(accessToken: string): Promise<any> {
Can we type this properly?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/utils/uuid.ts
> +  })
Could you add the source for this function here? The general rule is "don't roll your own crypto". Fine for me to copy it, I like reducing dependencies, but we should have a good source in my view :)

2020-12-07 20:51 UTC, philipstanislaus commented on package.json
> +    "start": "concurrently --kill-others-on-fail \"yarn onboard-api\"  \"yarn tinlake-ui\" -p name -n \"onboard-api,tinlake-ui\""
Cool 👍

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/controllers/agreement.controller.ts
> +    console.log(req.cookies)
Can we remove this? If not, use logging service to make available for log monitoring/aggregation?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/controllers/kyc.controller.ts
> +    if (!pool) throw new BadRequestException('Invalid pool')
I thought KYC was only once per user, not once per pool?

2020-12-07 20:51 UTC, philipstanislaus commented on onboard-api/src/controllers/kyc.controller.ts
> +    console.log({ redirectUrl })
Same comment here regarding logger?

2020-12-07 21:01 UTC, philipstanislaus requested changes

2020-12-07 21:01 UTC, philipstanislaus commented on tinlake-ui/components/OnboardModal/index.tsx
> +          {status?.kyc.url && status.agreements[0]?.signed && !status.agreements[0]?.counterSigned && (
This check (and others in this file) imply that there is only one agreement. Might want to change this to 
`status.agreements.every(a => a.signed)` and likewise in other places.

2020-12-08 08:12 UTC, offerijns commented on .github/workflows/onboard-api.yml
> +    # if: github.ref == 'refs/heads/main'
So this would run on the PR and I could test whether it worked already ;-)

2020-12-08 08:13 UTC, offerijns commented on e2e-tests/package.json
> +    "@centrifuge/tinlake-js": "3.0.0-develop.35",
Yes, the problem is that the workspace tinlake.js is missing in the Docker build of `e2e-tests`.

2020-12-08 08:13 UTC, offerijns commented on .github/workflows/tinlake-ui.yml
> -      - run: yarn lint
If you look closely, we're still running it, just not twice haha.

2020-12-08 08:14 UTC, offerijns commented on onboard-api/src/app.controller.ts
> +  }
We do need an endpoint at `/` which returns 200, for Kubernetes readiness checks. But I'll rename it :)

2020-12-08 08:30 UTC, offerijns commented on onboard-api/src/controllers/agreement.controller.ts
> +    console.log(req.cookies)
I'll discuss with Miguel but I think we should just use Stackdriver (GCP's built in logging solution). Works pretty well in my experience!

2020-12-08 08:32 UTC, offerijns commented on tinlake-ui/components/OnboardModal/index.tsx
> +    setModalIsOpen(false)
Because this method opens the modal for connecting your wallet, so we should hide the onboarding modal.

2020-12-08 08:46 UTC, offerijns commented on onboard-api/src/db/migrations/00001_setup/index.sql
> +  email varchar(255),
Let's discuss in a call.

2020-12-08 08:46 UTC, offerijns commented on onboard-api/src/main.ts
> +  app.use(cookieParser())
Let's discuss in a call.

2020-12-08 09:07 UTC, offerijns commented on onboard-api/src/controllers/kyc.controller.ts
> +    if (!pool) throw new BadRequestException('Invalid pool')
Yes but we're passing `poolId` here and retrieving the pool information so that we can redirect the user back to the pool for which he/she is currently onboarding.

2020-12-08 09:32 UTC, offerijns commented on onboard-api/src/services/docusign.service.ts
> +          email: 'jeroen+issuer@centrifuge.io',
We need a place to store the issuer data, like this. Let's discuss in a call.

2020-12-08 09:36 UTC, offerijns commented on tinlake-ui/components/OnboardModal/index.tsx
> +          {status?.kyc.url && status.agreements[0]?.signed && !status.agreements[0]?.counterSigned && (
Well the copy will also assume there's a single agreement, and for the foreseeable future that will be the case. Imo we should already account for multiple agreements in the backend (as we don't want to change the API or db schema later), but assume there's a single agreement in the FE.

2020-12-08 10:51 UTC, offerijns commented
> 1. There are no tests, but this the api is super critical (privacy and functionality wise, downtime/bugs will cost us users). Let's discuss how we want to approach that.

Agreed, let's discuss in a call!

> 2. There is no retry handling for requests to 3rd party services. I feel we should add that (potentially in the next iteration) to make sure we don't loose users due to networking issues etc.

Added :) 

> 3. Before merging, can we transform all security and conversion related TODOs into issues (e. g. potential drop outs of funnel)?

Done.

> 4. Note to ourselves: For production, we should use some stack tracing/logging service.

Agreed, but we could just use GCP Stackdriver. It will just pull the logs from the container logs, and works well in my experience.

> 5. Note to ourselves: we need opt-in for cookie in onboarding modal.

Let's also discuss in our call.

2020-12-08 14:12 UTC, offerijns commented on tinlake-ui/components/OnboardModal/index.tsx
> +          {status?.kyc.url && status.agreements[0]?.signed && !status.agreements[0]?.counterSigned && (
Fixed by using your suggestion!

2020-12-08 14:12 UTC, offerijns commented on onboard-api/src/main.ts
> +  app.use(cookieParser())
Removed cookies for now.

2020-12-08 14:15 UTC, merged