Update pool status view
centrifuge/apps pull request #431
Opened 2021-10-05 13:09 UTC by alessioscalici

### Description

This pull request applies the following design changes to the Poostatus section of the Pool overview page:

- Remove connection between asset and investment side and display both as columns
- New Title of section: "Pool Status"
- Asset side:
  - Add Titles: Asset & Liquidity
  - Rows under Assets
    - Remove average financing amount
  - Rows under Liquidity
    - Remove Reserve
    - Add Available Liquidity calculated as Available Liquidity = Reserve + Available Credit Line for Maker pools and Available Liquidity = Reserve for non-Maker pools
    - Rename Reserve Ratio to Cash drag
- Token/Investment side
  - Remove tranche values
  - Remove the % from the token price in the Drop component

Closes #428

### Approvals

- [ ] Dev
- [ ] Designer
- [ ] Product

### Screenshots

#### Large viewport

<img width="1188" alt="Screenshot 2021-10-05 at 15 03 17" src="https://user-images.githubusercontent.com/8630331/136028308-e5d5935e-6585-44ec-8bf5-68c96a0df5c5.png">

#### Small viewport

<img width="425" alt="Screenshot 2021-10-05 at 15 03 59" src="https://user-images.githubusercontent.com/8630331/136028321-1ba0d0a6-bb1d-48a0-929b-9594b3f85730.png">

### Impact

Tinlake UI, Pool overview page

2021-10-05 13:17 UTC, offerijns requested changes

2021-10-05 13:46 UTC, denniswell commented
@alessioscalici Looks good to me. One thing, apologies, the tooltip for the min tin risk buffer (in the screenshot would be on ([min 10.00]) got lost in the specs:

` Minimum TIN risk buffer`
`The TIN risk buffer is the current value of the junior tranche (TIN) in relation to the pool value. The minimum TIN risk buffer indicates the lower limit and ensures that senior investors in DROP are protected by a certain amount of TIN invested in the pool at any time.`

Also updated above

2021-10-05 15:28 UTC, alessioscalici commented on tinlake-ui/containers/Investment/View/InvestmentOverview.tsx
> +    ? poolData?.reserve.add(poolData?.maker?.creditline || new BN(0))
Good catch, thanks for the clarification! Changed!

2021-10-06 10:03 UTC, offerijns approved these changes
💪

2021-10-06 11:24 UTC, merged