Fabric dark mode
centrifuge/apps pull request #465
Opened 2021-10-14 14:02 UTC by onnovisser

### Description

Adds a dark color mode to the Fabric theme

### Approvals

- [x] Dev

### Screenshots
<img width="731" alt="image" src="https://user-images.githubusercontent.com/23527729/137332829-871f8ec4-8f05-4849-b39a-2a702a192b42.png">
<img width="317" alt="image" src="https://user-images.githubusercontent.com/23527729/137332890-f39f2885-8663-4a1a-baa6-b65e93ccb7c8.png">

2021-10-15 13:24 UTC, alessioscalici requested changes

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/altairDark.ts
> +    ...modes.dark.colors,
I think it would make sense to keep the "light" and "dark" modes in separate files, as we'll always use them separately and they should be mutually exclusive

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/altairLight.ts
> +import { modes } from './tokens/modes'
Same here, i would suggest to split the modes in 2 files and `import lightMode from './tokens/lightMode'`

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/index.ts
> +export const themes = {
I suggest to avoid exporting all the themes in a single object: if this file is used, all the included themes will be loaded in the application.

The themes would still be importable like this: `import altairDark from '@centrifuge/fabric/theme/altairDark'`. It's a bit more verbose, but it only happens once per application

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/tokens/modes.ts
> +export const modes = {
This file could be split in `lightMode.ts` and 'darkMode.ts', as they are mutually exclusive and can be imported separately, avoiding loading more config than necessary

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/tokens/breakpoints.ts
>  breakpoints.xlarge = breakpoints[3]
I suggest to rename the breakpoints as per design system (S, M, L and XL instead of large, xlarge etc)

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/tokens/brandColors.ts
> +export const brandColors = {
I suggest to split this file in 2: `brandAltair.ts` and `brandCentrifuge.ts`

The reason is, we don't need Centrifuge colors in Altair and vice-versa, so we might want to allow importing only one or the other (mutual exclusivity)

2021-10-15 13:24 UTC, alessioscalici commented on fabric/src/theme/tokens/baseColors.ts
> +  altairYellow: '#FAB961',
These are brand related colors, I would add them to the related brand colors files

2021-10-18 07:28 UTC, onnovisser commented on fabric/src/theme/tokens/modes.ts
> +export const modes = {
done

2021-10-18 07:28 UTC, onnovisser commented on fabric/src/theme/index.ts
> +export const themes = {
done

2021-10-18 07:55 UTC, alessioscalici commented on fabric/src/components/Card/index.ts
> +export const Card = styled(Box)<Props>((props) =>
Oh, didn't see it! Thanks!

2021-10-18 08:10 UTC, merged