feature: investor transaction list CSV
centrifuge/apps pull request #550
Opened 2021-12-14 17:11 UTC by AStox

### Description

This pull request adds a button to download the new investor transaction list CSV

### Approvals

- [ ] Dev
- [ ] Designer
- [ ] Product

### Screenshots

### Impact

This pull request impacts the profile page only.

2021-12-15 07:47 UTC, armandomistral commented on tinlake-ui/containers/Portfolio/index.tsx
> -              <Button label="Explore further investment opportunities" secondary size="small" />
@AStox, let's stick to using the button component here. But let's use type tertiary/text for it. Here's the hierarchy of button styles:
![image](https://user-images.githubusercontent.com/23652850/146144685-c368e283-0bb5-4372-b14c-bbd79bfa9abc.png)

2021-12-15 07:48 UTC, armandomistral commented on tinlake-ui/containers/Portfolio/index.tsx
> +                Download transactions
@AStox, let's use the button component of type "text/tertiary" for this action here (see other comment)…

2021-12-15 07:49 UTC, armandomistral requested changes
Use button component of type tertiary/text instead of box component for actions `Download transactions`, and `Browse pools`

2021-12-15 09:08 UTC, onnovisser commented on tinlake-ui/containers/Portfolio/index.tsx
> -              <Button label="Explore further investment opportunities" secondary size="small" />
@AStox The Axis Button has a "plain" variant
```
<Button
  plain
  icon={<FormNextLink style={{ transform: 'rotate(90deg)' }} />}
  label="Explore further investment opportunities"
/>
```

2021-12-15 19:51 UTC, AStox commented on tinlake-ui/containers/Portfolio/index.tsx
> +                Download transactions
I dont actually see this button type anywhere. But the one Onno suggested seems to work well:
`<Button
  plain
  icon={<FormNextLink />}
  label="Explore further investment opportunities"
/>`

2021-12-16 07:20 UTC, armandomistral commented on tinlake-ui/containers/Portfolio/index.tsx
> +                Download transactions
Perfect, "plain" is the one! I was not aware it's called this way in code. Changed the name to "plain" the in design system.

2022-01-05 19:38 UTC, jpangelle approved these changes
👍

2022-01-07 14:28 UTC, onnovisser approved these changes

2022-01-11 12:01 UTC, armandomistral commented on tinlake-ui/containers/Portfolio/index.tsx
> +              icon={<FormNextLink style={{ transform: 'rotate(90deg)' }} />}
@AStox, I've added an "arrow-down" icon to brand assets here: https://www.figma.com/file/Xbfgir0ZyOjgteEftT8sxY/Brand-assets?node-id=3421%3A541

2022-01-11 16:08 UTC, armandomistral approved these changes

2022-01-12 12:29 UTC, armandomistral requested changes
@AStox, please make the icon also turn blue when hovering over the button. This should be the standard behavior of the component. Currently the icon stays black when hovering, see https://www.loom.com/share/e6f6c9883fff47fb9d7a727dec5fe16b

2022-07-20 12:43 UTC, closed without merging