Add collection description in collection detail page
centrifuge/apps pull request #670
Opened 2022-03-03 04:01 UTC by alessioscalici

### Description

This pull request adds the collection description in collection detail page, as per latest discussions and figma spec

Closes #640 

### Approvals

- [ ] Dev
- [ ] Dev
- [ ] Designer
- [ ] Product

### Screenshots

<img width="1192" alt="Screenshot 2022-03-03 at 11 58 38" src="https://user-images.githubusercontent.com/8630331/156493696-bfb49d7d-f1ea-48d5-b41e-cf185ef65c2e.png">
<img width="1190" alt="Screenshot 2022-03-03 at 11 59 09" src="https://user-images.githubusercontent.com/8630331/156493700-b3132c13-4249-49fc-96ca-ad5a33851716.png">
<img width="1191" alt="Screenshot 2022-03-03 at 11 59 25" src="https://user-images.githubusercontent.com/8630331/156493703-9f47b603-2e6c-48f3-ba3f-b66d6c9d4641.png">

### Impact

2022-03-03 07:45 UTC, armandomistral requested changes
Thanks, @alessioscalici! When connecting "Bob" account, not Mint action is shown. If connected with Alice address, it's shown. Can you reproduce this? 
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/23652850/156519525-0d8aeaec-005c-4836-9385-ebefbeb61b38.png">

2022-03-03 07:45 UTC, armandomistral commented on nft-studio/src/pages/Collection.tsx
> +        <Stack ml={3} alignItems="flex-start">
@alessioscalici, please remove the left-hand margin of 24px of this text. The design spec was wrong (I had forgotten removing it when moving the part down below the description). Thank you

2022-03-03 09:51 UTC, onnovisser approved these changes

2022-03-04 01:20 UTC, alessioscalici commented
> Thanks, @alessioscalici! When connecting "Bob" account, no Mint action is shown. If connected with Alice address, it's shown. Can you reproduce this? <img alt="image" width="1442" src="https://user-images.githubusercontent.com/23652850/156519525-0d8aeaec-005c-4836-9385-ebefbeb61b38.png">

@armandomistral 
![image](https://user-images.githubusercontent.com/8630331/156680690-d0deb4ed-10e9-48b1-9e23-359abd77820a.png)

Only the collection owner can mint NFTs, and Alice is (was) the owner of that beautifully empty collection! So indeed it's a feature 😄

2022-03-04 01:21 UTC, alessioscalici commented on nft-studio/src/pages/Collection.tsx
> +        <Stack ml={3} alignItems="flex-start">
Sure, done!

2022-03-04 01:22 UTC, merged