Centrifuge App: Fix finance and repayment forms
centrifuge/apps pull request #875
Opened 2022-06-15 15:19 UTC by sophialittlejohn

### Description

This pull request...

#846 
#844

### Approvals

- [ ] Dev

2022-06-20 11:51 UTC, offerijns requested changes
Looks great! Tested the thousand separators in the preview, works perfectly 🔥 Just left a few minor comments.

2022-06-20 11:51 UTC, offerijns commented on centrifuge-app/src/utils/formatting.ts
> +}
This should probably accept a precision. Now it's implicitly rounding to a precision of 2 decimals. Something like:

```suggestion
export function roundDown(float: Decimal | number, precision: number = 2) {
  return Math.floor((float instanceof Decimal ? float.toNumber() : float) * 10**precision) / 10**precision
}
```

2022-06-20 11:51 UTC, offerijns commented on fabric/src/components/CurrencyInput/index.tsx
> +    handleChange?: (value: number) => void
I think `onChange` is more standard, and in line with `onSetMax`?

```suggestion
    onChange?: (value: number) => void
```

2022-06-20 11:51 UTC, offerijns commented on fabric/src/components/CurrencyInput/index.tsx
> +    const inputFormatted = formatThousandSeparator(Math.floor((inputProps.value as number) * 100) / 100)
Similar to `roundDown`, the decimals shown should be configurable, using a `decimals` argument on `CurrencyInput`.

2022-06-20 12:25 UTC, sophialittlejohn commented on fabric/src/components/CurrencyInput/index.tsx
> +    const inputFormatted = formatThousandSeparator(Math.floor((inputProps.value as number) * 100) / 100)
good call, we would definitely need it sooner or later 👍  I defaulted the precisions to `2` everywhere

2022-06-20 18:35 UTC, offerijns commented on centrifuge-app/src/pages/Loan/FinanceForm.tsx
> +  const allowedToBorrow: Record<LoanInfo['type'], boolean> = {
I'm not sure I follow this, why is this always `false` for bullet loans and credit lines?

2022-06-21 08:21 UTC, sophialittlejohn commented on centrifuge-app/src/pages/Loan/FinanceForm.tsx
> +  const allowedToBorrow: Record<LoanInfo['type'], boolean> = {
I added validation for BulletLoans and CreditLines. Can you please double check the logic? It seems a little too simple the way it is now...

2022-06-21 15:30 UTC, offerijns requested changes

2022-06-21 15:30 UTC, offerijns commented on centrifuge-app/src/pages/Loan/FinanceForm.tsx
> +      loan.totalRepaid.toDecimal().lt(initialCeiling),
I think this should be:
```suggestion
      loan.totalBorrowed.toDecimal().lt(initialCeiling),
```

2022-06-21 15:49 UTC, sophialittlejohn commented on centrifuge-app/src/pages/Loan/FinanceForm.tsx
> +      loan.totalRepaid.toDecimal().lt(initialCeiling),
good point, just noticed that with `totalRepaid` the form would still be open even if the `maxBorrowed` is reached

2022-06-21 16:40 UTC, offerijns approved these changes
LGTM 👍

2022-06-21 17:10 UTC, merged